---
development:
  cloud_name: jsam
  api_key: '323971932749269'
  api_secret: ziAguYAssQyobSAWgA3YQk3VlaA
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: jsam
  api_key: '323971932749269'
  api_secret: ziAguYAssQyobSAWgA3YQk3VlaA
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: jsam
  api_key: '323971932749269'
  api_secret: ziAguYAssQyobSAWgA3YQk3VlaA
  enhance_image_tag: true
  static_file_support: false
